### PR TITLE
Benchmarking

### PR DESCRIPTION
**Pull request by andyhall**
Hi,

I wrote some basic benchmarking that you might like to try. Just switch to the branch and view `/test/bench/` locally to see it.

The functionality is basically:
 1. When you press the "Start" button it create X components, Y entities, and randomly adds Z components to each entity. 
 2. Then it does the equivalent of running X processes each animation frame. That is, for each component it loops through all entities with that component and sums a value from their state object. 
 3. Finally when you press "Stop" it reports the time taken for init and the average time taken each frame to run the processes.

Let me know if you have comments! I'm done with the branch so if you like it feel free to merge/rebase onto master.

### CODE REVIEW

**Comment by AdrianGaudebert** [comment]
Wow! That is super nice! Here are some results on my computer: 

```
352 iterations over 200 components, 500 entities w/ 50 components each
init time 91.84 ms
average time 5.88 ms/iteration
checksum: 25000 sum/iteration
```

```
213 iterations over 2000 components, 5000 entities w/ 500 components each
init time 12599.10 ms
average time 1523.56 ms/iteration
checksum: 2500000 sum/iteration
```

I'm not sure how to interpret those though... Is it good? Is it not? 

Thanks!

**Comment by andyhall** [comment]
> I'm not sure how to interpret those though... Is it good? Is it not?

In concrete terms I have no idea! :smile: All the number tell by themselves is how fast your PC is. I made the benchmark basically for three things: 

 1. To show roughly how many entities/components are feasible for a game
 2. To simulate heavy use so that browser profiling tools have something to profile. With more work this could show if there are bottlenecks
 3. For comparison, so I can tell if any performance improvements are working or not

More on (3) soon :wink:

**Comment by andyhall** [comment]
Hi, just wondering if you saw my update on issue #18? No rush, just not sure if gh pinged you or not.

**Comment by AdrianGaudebert** [comment]
@andyhall hey, I did see it, but was in vacations and did not take time to look at it yet. I'll get on it asap. Thanks!

**Pull request merged**
